# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.kcp.io_frontproxies.yaml
- bases/operator.kcp.io_rootshards.yaml
- bases/operator.kcp.io_shards.yaml
- bases/operator.kcp.io_cacheservers.yaml
- bases/operator.kcp.io_kubeconfigs.yaml
- bases/operator.kcp.io_workspaceobjects.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches: []
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_kcpinstances.yaml
#- path: patches/cainjection_in_frontproxies.yaml
#- path: patches/cainjection_in_shards.yaml
#- path: patches/cainjection_in_cacheservers.yaml
#- path: patches/cainjection_in_kubeconfigs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

#configurations:
#- kustomizeconfig.yaml
